//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlotHooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotHook
    {
        public PlotHook()
        {
            this.Steps = new HashSet<Step>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Step> Steps { get; set; }
    }
}
